# Declare the language
language: python

# Command to install dependencies
install:
  - pip install -r requirements.txt

# Command to run tests
script:
  - pytest --cov-report term --cov=app/

# After success, send the coverage report to Coveralls 
after_success:
  - coveralls